name: Environment Variables and Secrets Demo

on:
  workflow_dispatch:
  push:
    branches:
      - master

# Workflow-level environment variable
env:
  APP_NAME: demo-app

jobs:
  env_secrets_job:
    runs-on: ubuntu-latest

    # Job-level environment variable
    env:
      ENVIRONMENT: dev

    steps:
      - name: Show workflow and job env vars
        run: |
          echo "App name: $APP_NAME"
          echo "Environment: $ENVIRONMENT"

      - name: Use step-level env variable
        env:
          STEP_MESSAGE: "Hello from step-level env"
        run: echo "$STEP_MESSAGE"

      - name: Use GitHub secret safely
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          echo "Connecting to database..."
          echo "DB password is: $DB_PASSWORD"
